spring:
    jms:
      servicebus:
        connection-string: Endpoint=sb://living-goods-service-bus.servicebus.windows.net/;SharedAccessKeyName=lg-sample-key;SharedAccessKey=Tz6KSFl7iJoCh70VPuR50Lp/JGuh9ORbmO3P3xsQ/QE=;EntityPath=living-goods-queue
    autoconfigure:
      exclude:
      -   org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      -   org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
azure:
  openMRSQueue: lg-appb-openMRSQueue
  dhis2Queue: lg-appb-dhis2Queue
  targetDHIS2Queue: lg-appa-dhis2Queue
  targetOpenMRSQueue: lg-appa-openMRSQueue
server:
  port: 8084
couchdb:
  url: https://smarthealth-subhi-test.lg-apps.com/
  username: subhi
  password: C7KrKxFfu3uUy2Kw
  database: medic
openmrs:
  openMRSUname: admin
  openMRSPassword: Admin123
dhis2:
  uname: admin
  password: district
  url: https://dhis2.livinggoods.net/
