aws:
  accessKey: AKIA32E6HVBNRUYJB2U2
  secretKey: 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
  region: us-east-2
  dhis2Queue: lg-appA-dhis2Queue
  openMRSQueue: lg-appA-openMRSQueue
  targetOpenMRSQueue: lg-appB-openMRSQueue
  targetDHIS2Queue: lg-appB-dhis2Queue
spring:
    jms:
      servicebus:
        connection-string: Endpoint=sb://living-goods-service-bus.servicebus.windows.net/;SharedAccessKeyName=lg-sample-key;SharedAccessKey=Tz6KSFl7iJoCh70VPuR50Lp/JGuh9ORbmO3P3xsQ/QE=;EntityPath=living-goods-queue
    autoconfigure:
      exclude:
      -   org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      -   org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
server:
  port: 8080
couchdb:
  url: https://smarthealth-subhi-test.lg-apps.com/
  username: subhi
  password: C7KrKxFfu3uUy2Kw
  database: medic
openmrs:
  openMRSUname: admin
  openMRSPassword: Admin123
dhis2:
  uname: admin
  password: district
  url: https://dhis2.livinggoods.net/