activeMQ:
  brokerURL: tcp://localhost:61616
  uname: admin
  password: admin
  dhis2Queue: lg-appB-dhis2Queue
  openMRSQueue: lg-appB-openMRSQueue
  targetDHIS2Queue: lg-appA-dhis2Queue
  targetOpenMRSQueue: lg-appA-openMRSQueue
spring:
    activemq:
        in-memory: false
        packages:
            trust-all: true
    jms:
      servicebus:
        connection-string: Endpoint=sb://living-goods-service-bus.servicebus.windows.net/;SharedAccessKeyName=lg-sample-key;SharedAccessKey=Tz6KSFl7iJoCh70VPuR50Lp/JGuh9ORbmO3P3xsQ/QE=;EntityPath=living-goods-queue
    autoconfigure:
      exclude:
      -   org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      -   org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
server:
  port: 8080
couchdb:
  url: https://smarthealth-subhi-test.lg-apps.com/
  username: medic
  password: c40f41f136a6cdffcgj
  database: medic
openmrs:
  openMRSUname: admin
  openMRSPassword: Admin123
dhis2:
  uname: admin
  password: district
  url: https://dhis2.livinggoods.net/
